const SIN_ICON_DATA = {
  "분노": "images/sins/1.webp",
  "색욕": "images/sins/2.webp",
  "나태": "images/sins/3.webp",
  "탐식": "images/sins/4.webp",
  "우울": "images/sins/5.webp",
  "오만": "images/sins/6.webp",
  "질투": "images/sins/7.webp",
};

const SINNER_ICON_DATA = {
  "이상": "images/sinners/1.webp",
  "파우스트": "images/sinners/2.webp",
  "돈키호테": "images/sinners/3.webp",
  "료슈": "images/sinners/4.webp",
  "뫼르소": "images/sinners/5.webp",
  "홍루": "images/sinners/6.webp",
  "히스클리프": "images/sinners/7.webp",
  "이스마엘": "images/sinners/8.webp",
  "로쟈": "images/sinners/9.webp",
  "싱클레어": "images/sinners/10.webp",
  "오티스": "images/sinners/11.webp",
  "그레고르": "images/sinners/12.webp",
};

const IDENTITY_BANNER_SYNCED_DATA = {
  "홍루|동부 섕크 협회 3과": "images/banners_synced/1.webp",
  "이상|LCE E.G.O::차원찢개": "images/banners_synced/2.webp",
  "파우스트|새벽 사무소 해결사": "images/banners_synced/3.webp",
  "그레고르|새벽 사무소 대표": "images/banners_synced/4.webp",
  "히스클리프|거미집 엄지 제자": "images/banners_synced/5.webp",
  "로쟈|거미집 엄지 아비": "images/banners_synced/6.webp",
  "홍루|S사 추노꾼": "images/banners_synced/7.webp",
  "이스마엘|LCD 현장추리팀": "images/banners_synced/8.webp",
  "오티스|거미집 중지 아비": "images/banners_synced/9.webp",
  "료슈|거미집의 검": "images/banners_synced/10.webp",
  "히스클리프|중지 작은 형님": "images/banners_synced/11.webp",
  "뫼르소|약지 야수파 스튜던트": "images/banners_synced/12.webp",
  "로쟈|약지 야수파 도슨트": "images/banners_synced/13.webp",
  "파우스트|거미집 약지 제자": "images/banners_synced/14.webp",
  "홍루|거미집 약지 아비": "images/banners_synced/15.webp",
  "그레고르|LCE E.G.O::AEDD": "images/banners_synced/16.webp",
  "료슈|로보토미 E.G.O::잔향 · 외로움": "images/banners_synced/17.webp",
  "뫼르소|로보토미 E.G.O::호넷【변조】": "images/banners_synced/18.webp",
  "이상|거미집 검지 아비": "images/banners_synced/19.webp",
  "싱클레어|거미집 소지 제자": "images/banners_synced/20.webp",
  "그레고르|로보토미 E.G.O::램프": "images/banners_synced/21.webp",
  "이스마엘|거미집 중지 제자": "images/banners_synced/22.webp",
  "돈키호테|검지 대행자 - 개화 E.G.O::대행": "images/banners_synced/23.webp",
  "파우스트|검지 수행자:【쪽지】": "images/banners_synced/24.webp",
  "오티스|LCA 우제트 선봉 3팀 팀장": "images/banners_synced/25.webp",
  "로쟈|R사 제 4무리 순록팀": "images/banners_synced/26.webp",
  "료슈|홍원 방랑무사": "images/banners_synced/27.webp",
  "돈키호테|흑수 - 미": "images/banners_synced/28.webp",
  "히스클리프|흑수 - 유 필두": "images/banners_synced/29.webp",
  "이스마엘|정사무소 대표": "images/banners_synced/30.webp",
  "그레고르|밤의 송곳 카피타노": "images/banners_synced/31.webp",
  "뫼르소|라만차랜드 왕자": "images/banners_synced/32.webp",
  "히스클리프|W사 4등급 정리 요원 - CCA": "images/banners_synced/33.webp",
  "파우스트|동부 시 협회 3과": "images/banners_synced/34.webp",
  "료슈|N사 E.G.O::경멸, 경외": "images/banners_synced/35.webp",
  "이상|흑수 - 오 필두": "images/banners_synced/36.webp",
  "싱클레어|흑수 - 유": "images/banners_synced/37.webp",
  "홍루|홍원 군주": "images/banners_synced/38.webp",
  "오티스|T사 3등급 강력징수직 직원": "images/banners_synced/39.webp",
  "돈키호테|로보토미 E.G.O::사랑과 증오의 이름으로": "images/banners_synced/40.webp",
  "로쟈|로보토미 E.G.O::눈물로 벼려낸 검": "images/banners_synced/41.webp",
  "이상|N사 E.G.O::흉탄": "images/banners_synced/42.webp",
  "뫼르소|동부 엄지 카포 IIII": "images/banners_synced/43.webp",
  "싱클레어|동부 엄지 솔다토 II": "images/banners_synced/44.webp",
  "이스마엘|가주 후보": "images/banners_synced/45.webp",
  "파우스트|흑수 - 묘 필두": "images/banners_synced/46.webp",
  "로쟈|흑수 - 사": "images/banners_synced/47.webp",
  "그레고르|흑수 - 사": "images/banners_synced/48.webp",
  "홍루|R사 제 4무리 순록팀": "images/banners_synced/49.webp",
  "싱클레어|중지 작은 아우": "images/banners_synced/50.webp",
  "료슈|흑수 - 묘": "images/banners_synced/51.webp",
  "오티스|흑수 - 묘": "images/banners_synced/52.webp",
  "돈키호테|동부 섕크 협회 3과": "images/banners_synced/53.webp",
  "그레고르|불주먹 사무소 생존자": "images/banners_synced/54.webp",
  "이상|남부 리우 협회 3과": "images/banners_synced/55.webp",
  "히스클리프|흑운회 와카슈": "images/banners_synced/56.webp",
  "이스마엘|흑운회 부조장": "images/banners_synced/57.webp",
  "이상|LCE E.G.O::초롱": "images/banners_synced/58.webp",
  "파우스트|LCE E.G.O::홍염살": "images/banners_synced/59.webp",
  "홍루|마침표 사무소 대표": "images/banners_synced/60.webp",
  "히스클리프|마침표 사무소 해결사": "images/banners_synced/61.webp",
  "돈키호테|라만차랜드 실장": "images/banners_synced/62.webp",
  "싱클레어|북부 제뱌찌 협회 3과": "images/banners_synced/63.webp",
  "로쟈|라만차랜드 공주": "images/banners_synced/64.webp",
  "그레고르|라만차랜드 신부": "images/banners_synced/65.webp",
  "홍루|송곳니 사냥 사무소 해결사": "images/banners_synced/66.webp",
  "오티스|라만차랜드 이발사": "images/banners_synced/67.webp",
  "뫼르소|서부 섕크 협회 3과": "images/banners_synced/68.webp",
  "싱클레어|서부 츠바이 협회 3과": "images/banners_synced/69.webp",
  "이스마엘|서부 츠바이 협회 3과": "images/banners_synced/70.webp",
  "로쟈|북부 제뱌찌 협회 3과": "images/banners_synced/71.webp",
  "이상|로보토미 E.G.O::엄숙한 애도": "images/banners_synced/72.webp",
  "료슈|로보토미 E.G.O::적안 · 참회": "images/banners_synced/73.webp",
  "히스클리프|와일드헌트": "images/banners_synced/74.webp",
  "파우스트|멀티크랙 사무소 대표": "images/banners_synced/75.webp",
  "히스클리프|멀티크랙 사무소 해결사": "images/banners_synced/76.webp",
  "오티스|W사 3등급 정리 요원 팀장": "images/banners_synced/77.webp",
  "뫼르소|남부 디에치 협회 4과 부장": "images/banners_synced/78.webp",
  "돈키호테|T사 3등급 징수직 직원": "images/banners_synced/79.webp",
  "로쟈|T사 2등급 징수직 직원": "images/banners_synced/80.webp",
  "료슈|20구 유로지비": "images/banners_synced/81.webp",
  "홍루|20구 유로지비": "images/banners_synced/82.webp",
  "이상|약지 점묘파 스튜던트": "images/banners_synced/83.webp",
  "오티스|약지 점묘파 스튜던트": "images/banners_synced/84.webp",
  "싱클레어|새벽 사무소 해결사": "images/banners_synced/85.webp",
  "료슈|에드가 가문 치프 버틀러": "images/banners_synced/86.webp",
  "이스마엘|에드가 가문 버틀러": "images/banners_synced/87.webp",
  "파우스트|워더링하이츠 버틀러": "images/banners_synced/88.webp",
  "그레고르|에드가 가문 승계자": "images/banners_synced/89.webp",
  "뫼르소|데드레빗츠 보스": "images/banners_synced/90.webp",
  "오티스|워더링하이츠 치프 버틀러": "images/banners_synced/91.webp",
  "히스클리프|남부 외우피 협회 3과": "images/banners_synced/92.webp",
  "료슈|남부 리우 협회 4과": "images/banners_synced/93.webp",
  "로쟈|남부 리우 협회 4과 부장": "images/banners_synced/94.webp",
  "파우스트|검계 살수": "images/banners_synced/95.webp",
  "돈키호테|검계 살수": "images/banners_synced/96.webp",
  "뫼르소|검계 우두머리": "images/banners_synced/97.webp",
  "그레고르|흑운회 부조장": "images/banners_synced/98.webp",
  "이스마엘|피쿼드호 선장": "images/banners_synced/99.webp",
  "이상|남부 디에치 협회 4과": "images/banners_synced/100.webp",
  "홍루|남부 디에치 협회 4과": "images/banners_synced/101.webp",
  "돈키호테|로보토미 E.G.O::초롱": "images/banners_synced/102.webp",
  "오티스|로보토미 E.G.O::마탄": "images/banners_synced/103.webp",
  "싱클레어|남부 섕크 협회 4과 부장": "images/banners_synced/104.webp",
  "오티스|남부 섕크 협회 4과": "images/banners_synced/105.webp",
  "이상|피쿼드호 일등 항해사": "images/banners_synced/106.webp",
  "히스클리프|피쿼드호 작살잡이": "images/banners_synced/107.webp",
  "돈키호테|중지 작은 아우": "images/banners_synced/108.webp",
  "뫼르소|중지 작은 아우": "images/banners_synced/109.webp",
  "료슈|LCCB 대리": "images/banners_synced/110.webp",
  "그레고르|쌍갈고리 해적단 부선장": "images/banners_synced/111.webp",
  "이상|W사 3등급 정리 요원": "images/banners_synced/112.webp",
  "파우스트|로보토미 E.G.O::후회": "images/banners_synced/113.webp",
  "홍루|갈고리 사무소 해결사": "images/banners_synced/114.webp",
  "로쟈|남부 디에치 협회 4과": "images/banners_synced/115.webp",
  "이상|어금니 사무소 해결사": "images/banners_synced/116.webp",
  "오티스|어금니 사무소 해결사": "images/banners_synced/117.webp",
  "파우스트|남부 세븐 협회 4과": "images/banners_synced/118.webp",
  "히스클리프|남부 세븐 협회 4과": "images/banners_synced/119.webp",
  "료슈|W사 3등급 정리 요원": "images/banners_synced/120.webp",
  "홍루|W사 2등급 정리 요원": "images/banners_synced/121.webp",
  "파우스트|남부 츠바이 협회 4과": "images/banners_synced/122.webp",
  "그레고르|남부 츠바이 협회 4과": "images/banners_synced/123.webp",
  "이스마엘|어금니 보트 센터 해결사": "images/banners_synced/124.webp",
  "싱클레어|어금니 보트 센터 해결사": "images/banners_synced/125.webp",
  "돈키호테|남부 섕크 협회 5과 부장": "images/banners_synced/126.webp",
  "뫼르소|R사 제 4무리 코뿔소팀": "images/banners_synced/127.webp",
  "로쟈|남부 츠바이 협회 5과": "images/banners_synced/128.webp",
  "이스마엘|남부 리우 협회 4과": "images/banners_synced/129.webp",
  "홍루|K사 3등급 적출직 직원": "images/banners_synced/130.webp",
  "싱클레어|로보토미 E.G.O::홍적": "images/banners_synced/131.webp",
  "이상|개화 E.G.O::동백": "images/banners_synced/132.webp",
  "이스마엘|로보토미 E.G.O::출렁임": "images/banners_synced/133.webp",
  "히스클리프|로보토미 E.G.O::여우비": "images/banners_synced/134.webp",
  "그레고르|장미스패너 공방 해결사": "images/banners_synced/135.webp",
  "뫼르소|장미스패너 공방 해결사": "images/banners_synced/136.webp",
  "로쟈|장미스패너 공방 대표": "images/banners_synced/137.webp",
  "돈키호테|N사 중간 망치": "images/banners_synced/138.webp",
  "싱클레어|쥐어들 자": "images/banners_synced/139.webp",
  "료슈|료.고.파. 주방장": "images/banners_synced/140.webp",
  "그레고르|료.고.파. 조수": "images/banners_synced/141.webp",
  "홍루|남부 리우 협회 5과": "images/banners_synced/142.webp",
  "오티스|남부 세븐 협회 6과 부장": "images/banners_synced/143.webp",
  "파우스트|쥐는 자": "images/banners_synced/144.webp",
  "히스클리프|N사 작은 망치": "images/banners_synced/145.webp",
  "뫼르소|N사 큰 망치": "images/banners_synced/146.webp",
  "로쟈|N사 중간 망치": "images/banners_synced/147.webp",
  "이상|검계 살수": "images/banners_synced/148.webp",
  "이상|남부 세븐 협회 6과": "images/banners_synced/149.webp",
  "파우스트|W사 2등급 정리 요원": "images/banners_synced/150.webp",
  "파우스트|살아남은 로보토미 직원": "images/banners_synced/151.webp",
  "돈키호테|W사 3등급 정리 요원": "images/banners_synced/152.webp",
  "돈키호테|남부 시 협회 5과 부장": "images/banners_synced/153.webp",
  "료슈|흑운회 와카슈": "images/banners_synced/154.webp",
  "료슈|남부 세븐 협회 6과": "images/banners_synced/155.webp",
  "뫼르소|W사 2등급 정리 요원": "images/banners_synced/156.webp",
  "뫼르소|남부 리우 협회 6과": "images/banners_synced/157.webp",
  "홍루|콩콩이파 두목": "images/banners_synced/158.webp",
  "홍루|흑운회 와카슈": "images/banners_synced/159.webp",
  "히스클리프|R사 제 4무리 토끼팀": "images/banners_synced/160.webp",
  "히스클리프|남부 시 협회 5과": "images/banners_synced/161.webp",
  "이스마엘|R사 제 4무리 순록팀": "images/banners_synced/162.webp",
  "이스마엘|남부 시 협회 5과": "images/banners_synced/163.webp",
  "이스마엘|LCCB 대리": "images/banners_synced/164.webp",
  "로쟈|흑운회 와카슈": "images/banners_synced/165.webp",
  "로쟈|LCCB 대리": "images/banners_synced/166.webp",
  "싱클레어|검계 살수": "images/banners_synced/167.webp",
  "싱클레어|남부 츠바이 협회 6과": "images/banners_synced/168.webp",
  "싱클레어|마리아치 보스": "images/banners_synced/169.webp",
  "오티스|검계 살수": "images/banners_synced/170.webp",
  "오티스|G사 부장": "images/banners_synced/171.webp",
  "그레고르|G사 일등대리": "images/banners_synced/172.webp",
  "그레고르|남부 리우 협회 6과": "images/banners_synced/173.webp",
};

const IDENTITY_BANNER_NORMAL_DATA = {
  "홍루|동부 섕크 협회 3과": "images/banners_normal/1.webp",
  "이상|LCE E.G.O::차원찢개": "images/banners_normal/2.webp",
  "파우스트|새벽 사무소 해결사": "images/banners_normal/3.webp",
  "그레고르|새벽 사무소 대표": "images/banners_normal/4.webp",
  "히스클리프|거미집 엄지 제자": "images/banners_normal/5.webp",
  "로쟈|거미집 엄지 아비": "images/banners_normal/6.webp",
  "홍루|S사 추노꾼": "images/banners_normal/7.webp",
  "이스마엘|LCD 현장추리팀": "images/banners_normal/8.webp",
  "오티스|거미집 중지 아비": "images/banners_normal/9.webp",
  "료슈|거미집의 검": "images/banners_normal/10.webp",
  "히스클리프|중지 작은 형님": "images/banners_normal/11.webp",
  "뫼르소|약지 야수파 스튜던트": "images/banners_normal/12.webp",
  "로쟈|약지 야수파 도슨트": "images/banners_normal/13.webp",
  "파우스트|거미집 약지 제자": "images/banners_normal/14.webp",
  "홍루|거미집 약지 아비": "images/banners_normal/15.webp",
  "그레고르|LCE E.G.O::AEDD": "images/banners_normal/16.webp",
  "료슈|로보토미 E.G.O::잔향 · 외로움": "images/banners_normal/17.webp",
  "뫼르소|로보토미 E.G.O::호넷【변조】": "images/banners_normal/18.webp",
  "이상|거미집 검지 아비": "images/banners_normal/19.webp",
  "싱클레어|거미집 소지 제자": "images/banners_normal/20.webp",
  "그레고르|로보토미 E.G.O::램프": "images/banners_normal/21.webp",
  "이스마엘|거미집 중지 제자": "images/banners_normal/22.webp",
  "돈키호테|검지 대행자 - 개화 E.G.O::대행": "images/banners_normal/23.webp",
  "파우스트|검지 수행자:【쪽지】": "images/banners_normal/24.webp",
  "오티스|LCA 우제트 선봉 3팀 팀장": "images/banners_normal/25.webp",
  "로쟈|R사 제 4무리 순록팀": "images/banners_normal/26.webp",
  "료슈|홍원 방랑무사": "images/banners_normal/27.webp",
  "돈키호테|흑수 - 미": "images/banners_normal/28.webp",
  "히스클리프|흑수 - 유 필두": "images/banners_normal/29.webp",
  "이스마엘|정사무소 대표": "images/banners_normal/30.webp",
  "그레고르|밤의 송곳 카피타노": "images/banners_normal/31.webp",
  "뫼르소|라만차랜드 왕자": "images/banners_normal/32.webp",
  "히스클리프|W사 4등급 정리 요원 - CCA": "images/banners_normal/33.webp",
  "파우스트|동부 시 협회 3과": "images/banners_normal/34.webp",
  "료슈|N사 E.G.O::경멸, 경외": "images/banners_normal/35.webp",
  "이상|흑수 - 오 필두": "images/banners_normal/36.webp",
  "싱클레어|흑수 - 유": "images/banners_normal/37.webp",
  "홍루|홍원 군주": "images/banners_normal/38.webp",
  "오티스|T사 3등급 강력징수직 직원": "images/banners_normal/39.webp",
  "돈키호테|로보토미 E.G.O::사랑과 증오의 이름으로": "images/banners_normal/40.webp",
  "로쟈|로보토미 E.G.O::눈물로 벼려낸 검": "images/banners_normal/41.webp",
  "이상|N사 E.G.O::흉탄": "images/banners_normal/42.webp",
  "뫼르소|동부 엄지 카포 IIII": "images/banners_normal/43.webp",
  "싱클레어|동부 엄지 솔다토 II": "images/banners_normal/44.webp",
  "이스마엘|가주 후보": "images/banners_normal/45.webp",
  "파우스트|흑수 - 묘 필두": "images/banners_normal/46.webp",
  "로쟈|흑수 - 사": "images/banners_normal/47.webp",
  "그레고르|흑수 - 사": "images/banners_normal/48.webp",
  "홍루|R사 제 4무리 순록팀": "images/banners_normal/49.webp",
  "싱클레어|중지 작은 아우": "images/banners_normal/50.webp",
  "료슈|흑수 - 묘": "images/banners_normal/51.webp",
  "오티스|흑수 - 묘": "images/banners_normal/52.webp",
  "돈키호테|동부 섕크 협회 3과": "images/banners_normal/53.webp",
  "그레고르|불주먹 사무소 생존자": "images/banners_normal/54.webp",
  "이상|남부 리우 협회 3과": "images/banners_normal/55.webp",
  "히스클리프|흑운회 와카슈": "images/banners_normal/56.webp",
  "이스마엘|흑운회 부조장": "images/banners_normal/57.webp",
  "이상|LCE E.G.O::초롱": "images/banners_normal/58.webp",
  "파우스트|LCE E.G.O::홍염살": "images/banners_normal/59.webp",
  "홍루|마침표 사무소 대표": "images/banners_normal/60.webp",
  "히스클리프|마침표 사무소 해결사": "images/banners_normal/61.webp",
  "돈키호테|라만차랜드 실장": "images/banners_normal/62.webp",
  "싱클레어|북부 제뱌찌 협회 3과": "images/banners_normal/63.webp",
  "로쟈|라만차랜드 공주": "images/banners_normal/64.webp",
  "그레고르|라만차랜드 신부": "images/banners_normal/65.webp",
  "홍루|송곳니 사냥 사무소 해결사": "images/banners_normal/66.webp",
  "오티스|라만차랜드 이발사": "images/banners_normal/67.webp",
  "뫼르소|서부 섕크 협회 3과": "images/banners_normal/68.webp",
  "싱클레어|서부 츠바이 협회 3과": "images/banners_normal/69.webp",
  "이스마엘|서부 츠바이 협회 3과": "images/banners_normal/70.webp",
  "로쟈|북부 제뱌찌 협회 3과": "images/banners_normal/71.webp",
  "이상|로보토미 E.G.O::엄숙한 애도": "images/banners_normal/72.webp",
  "료슈|로보토미 E.G.O::적안 · 참회": "images/banners_normal/73.webp",
  "히스클리프|와일드헌트": "images/banners_normal/74.webp",
  "파우스트|멀티크랙 사무소 대표": "images/banners_normal/75.webp",
  "히스클리프|멀티크랙 사무소 해결사": "images/banners_normal/76.webp",
  "오티스|W사 3등급 정리 요원 팀장": "images/banners_normal/77.webp",
  "뫼르소|남부 디에치 협회 4과 부장": "images/banners_normal/78.webp",
  "돈키호테|T사 3등급 징수직 직원": "images/banners_normal/79.webp",
  "로쟈|T사 2등급 징수직 직원": "images/banners_normal/80.webp",
  "료슈|20구 유로지비": "images/banners_normal/81.webp",
  "홍루|20구 유로지비": "images/banners_normal/82.webp",
  "이상|약지 점묘파 스튜던트": "images/banners_normal/83.webp",
  "오티스|약지 점묘파 스튜던트": "images/banners_normal/84.webp",
  "싱클레어|새벽 사무소 해결사": "images/banners_normal/85.webp",
  "료슈|에드가 가문 치프 버틀러": "images/banners_normal/86.webp",
  "이스마엘|에드가 가문 버틀러": "images/banners_normal/87.webp",
  "파우스트|워더링하이츠 버틀러": "images/banners_normal/88.webp",
  "그레고르|에드가 가문 승계자": "images/banners_normal/89.webp",
  "뫼르소|데드레빗츠 보스": "images/banners_normal/90.webp",
  "오티스|워더링하이츠 치프 버틀러": "images/banners_normal/91.webp",
  "히스클리프|남부 외우피 협회 3과": "images/banners_normal/92.webp",
  "료슈|남부 리우 협회 4과": "images/banners_normal/93.webp",
  "로쟈|남부 리우 협회 4과 부장": "images/banners_normal/94.webp",
  "파우스트|검계 살수": "images/banners_normal/95.webp",
  "돈키호테|검계 살수": "images/banners_normal/96.webp",
  "뫼르소|검계 우두머리": "images/banners_normal/97.webp",
  "그레고르|흑운회 부조장": "images/banners_normal/98.webp",
  "이스마엘|피쿼드호 선장": "images/banners_normal/99.webp",
  "이상|남부 디에치 협회 4과": "images/banners_normal/100.webp",
  "홍루|남부 디에치 협회 4과": "images/banners_normal/101.webp",
  "돈키호테|로보토미 E.G.O::초롱": "images/banners_normal/102.webp",
  "오티스|로보토미 E.G.O::마탄": "images/banners_normal/103.webp",
  "싱클레어|남부 섕크 협회 4과 부장": "images/banners_normal/104.webp",
  "오티스|남부 섕크 협회 4과": "images/banners_normal/105.webp",
  "이상|피쿼드호 일등 항해사": "images/banners_normal/106.webp",
  "히스클리프|피쿼드호 작살잡이": "images/banners_normal/107.webp",
  "돈키호테|중지 작은 아우": "images/banners_normal/108.webp",
  "뫼르소|중지 작은 아우": "images/banners_normal/109.webp",
  "료슈|LCCB 대리": "images/banners_normal/110.webp",
  "그레고르|쌍갈고리 해적단 부선장": "images/banners_normal/111.webp",
  "이상|W사 3등급 정리 요원": "images/banners_normal/112.webp",
  "파우스트|로보토미 E.G.O::후회": "images/banners_normal/113.webp",
  "홍루|갈고리 사무소 해결사": "images/banners_normal/114.webp",
  "로쟈|남부 디에치 협회 4과": "images/banners_normal/115.webp",
  "이상|어금니 사무소 해결사": "images/banners_normal/116.webp",
  "오티스|어금니 사무소 해결사": "images/banners_normal/117.webp",
  "파우스트|남부 세븐 협회 4과": "images/banners_normal/118.webp",
  "히스클리프|남부 세븐 협회 4과": "images/banners_normal/119.webp",
  "료슈|W사 3등급 정리 요원": "images/banners_normal/120.webp",
  "홍루|W사 2등급 정리 요원": "images/banners_normal/121.webp",
  "파우스트|남부 츠바이 협회 4과": "images/banners_normal/122.webp",
  "그레고르|남부 츠바이 협회 4과": "images/banners_normal/123.webp",
  "이스마엘|어금니 보트 센터 해결사": "images/banners_normal/124.webp",
  "싱클레어|어금니 보트 센터 해결사": "images/banners_normal/125.webp",
  "돈키호테|남부 섕크 협회 5과 부장": "images/banners_normal/126.webp",
  "뫼르소|R사 제 4무리 코뿔소팀": "images/banners_normal/127.webp",
  "로쟈|남부 츠바이 협회 5과": "images/banners_normal/128.webp",
  "이스마엘|남부 리우 협회 4과": "images/banners_normal/129.webp",
  "홍루|K사 3등급 적출직 직원": "images/banners_normal/130.webp",
  "싱클레어|로보토미 E.G.O::홍적": "images/banners_normal/131.webp",
  "이상|개화 E.G.O::동백": "images/banners_normal/132.webp",
  "이스마엘|로보토미 E.G.O::출렁임": "images/banners_normal/133.webp",
  "히스클리프|로보토미 E.G.O::여우비": "images/banners_normal/134.webp",
  "그레고르|장미스패너 공방 해결사": "images/banners_normal/135.webp",
  "뫼르소|장미스패너 공방 해결사": "images/banners_normal/136.webp",
  "로쟈|장미스패너 공방 대표": "images/banners_normal/137.webp",
  "돈키호테|N사 중간 망치": "images/banners_normal/138.webp",
  "싱클레어|쥐어들 자": "images/banners_normal/139.webp",
  "료슈|료.고.파. 주방장": "images/banners_normal/140.webp",
  "그레고르|료.고.파. 조수": "images/banners_normal/141.webp",
  "홍루|남부 리우 협회 5과": "images/banners_normal/142.webp",
  "오티스|남부 세븐 협회 6과 부장": "images/banners_normal/143.webp",
  "파우스트|쥐는 자": "images/banners_normal/144.webp",
  "히스클리프|N사 작은 망치": "images/banners_normal/145.webp",
  "뫼르소|N사 큰 망치": "images/banners_normal/146.webp",
  "로쟈|N사 중간 망치": "images/banners_normal/147.webp",
  "이상|검계 살수": "images/banners_normal/148.webp",
  "이상|남부 세븐 협회 6과": "images/banners_normal/149.webp",
  "이상|LCB 수감자": "images/banners_normal/150.webp",
  "파우스트|W사 2등급 정리 요원": "images/banners_normal/151.webp",
  "파우스트|살아남은 로보토미 직원": "images/banners_normal/152.webp",
  "파우스트|LCB 수감자": "images/banners_normal/153.webp",
  "돈키호테|W사 3등급 정리 요원": "images/banners_normal/154.webp",
  "돈키호테|남부 시 협회 5과 부장": "images/banners_normal/155.webp",
  "돈키호테|LCB 수감자": "images/banners_normal/156.webp",
  "료슈|흑운회 와카슈": "images/banners_normal/157.webp",
  "료슈|남부 세븐 협회 6과": "images/banners_normal/158.webp",
  "료슈|LCB 수감자": "images/banners_normal/159.webp",
  "뫼르소|W사 2등급 정리 요원": "images/banners_normal/160.webp",
  "뫼르소|남부 리우 협회 6과": "images/banners_normal/161.webp",
  "뫼르소|LCB 수감자": "images/banners_normal/162.webp",
  "홍루|콩콩이파 두목": "images/banners_normal/163.webp",
  "홍루|흑운회 와카슈": "images/banners_normal/164.webp",
  "홍루|LCB 수감자": "images/banners_normal/165.webp",
  "히스클리프|R사 제 4무리 토끼팀": "images/banners_normal/166.webp",
  "히스클리프|남부 시 협회 5과": "images/banners_normal/167.webp",
  "히스클리프|LCB 수감자": "images/banners_normal/168.webp",
  "이스마엘|R사 제 4무리 순록팀": "images/banners_normal/169.webp",
  "이스마엘|남부 시 협회 5과": "images/banners_normal/170.webp",
  "이스마엘|LCCB 대리": "images/banners_normal/171.webp",
  "이스마엘|LCB 수감자": "images/banners_normal/172.webp",
  "로쟈|흑운회 와카슈": "images/banners_normal/173.webp",
  "로쟈|LCCB 대리": "images/banners_normal/174.webp",
  "로쟈|LCB 수감자": "images/banners_normal/175.webp",
  "싱클레어|검계 살수": "images/banners_normal/176.webp",
  "싱클레어|남부 츠바이 협회 6과": "images/banners_normal/177.webp",
  "싱클레어|마리아치 보스": "images/banners_normal/178.webp",
  "싱클레어|LCB 수감자": "images/banners_normal/179.webp",
  "오티스|검계 살수": "images/banners_normal/180.webp",
  "오티스|G사 부장": "images/banners_normal/181.webp",
  "오티스|LCB 수감자": "images/banners_normal/182.webp",
  "그레고르|G사 일등대리": "images/banners_normal/183.webp",
  "그레고르|남부 리우 협회 6과": "images/banners_normal/184.webp",
  "그레고르|LCB 수감자": "images/banners_normal/185.webp",
};

const KEYWORD_ICON_DATA = {
  "공격 레벨": "images/keywords/1.webp",
  "광신": "images/keywords/2.webp",
  "나비": "images/keywords/3.webp",
  "도발치": "images/keywords/4.webp",
  "방어 레벨": "images/keywords/5.webp",
  "보호": "images/keywords/6.webp",
  "속박": "images/keywords/7.webp",
  "신속": "images/keywords/8.webp",
  "진동": "images/keywords/9.webp",
  "출혈": "images/keywords/10.webp",
  "충전 역장": "images/keywords/11.webp",
  "충전": "images/keywords/12.webp",
  "취약": "images/keywords/13.webp",
  "침잠": "images/keywords/14.webp",
  "탄환": "images/keywords/15.webp",
  "파열": "images/keywords/16.webp",
  "패닉": "images/keywords/17.webp",
  "합 위력": "images/keywords/18.webp",
  "호흡": "images/keywords/19.webp",
  "화상": "images/keywords/20.webp",
  "구더기": "images/keywords/21.webp",
  "저주": "images/keywords/22.webp",
  "버림": "images/keywords/24.webp",
  "올가미": "images/keywords/25.webp",
  "흑운도": "images/keywords/26.webp",
  "히스테리": "images/keywords/27.webp",
  "카르마": "images/keywords/28.webp",
  "저택의 메아리": "images/keywords/29.webp",
  "시간 대여": "images/keywords/30.webp",
  "본국검술": "images/keywords/31.webp",
  "전략적 휴식 복지 모드": "images/keywords/32.webp",
  "마법소녀 등장!": "images/keywords/33.webp",
  "매지컬 아르카나": "images/keywords/34.webp",
  "악당 표식": "images/keywords/35.webp",
  "역변-리버스드": "images/keywords/36.webp",
  "시간 유예": "images/keywords/37.webp",
  "재장전": "images/keywords/38.webp",
  "혈염[血炎]": "images/keywords/39.webp",
  "참선": "images/keywords/40.webp",
  "각력【묘】": "images/keywords/41.webp",
};

const GIFT_ICON_DATA = {
  "날개 모양 양초": "images/gifts/1.webp",
};

const UI_ICON_DATA = {
  "skillFrame": "images/ui/1.webp",
};

const IDENTITY_SKILL_ICON_DATA = {
  "이상|LCB 수감자": {skill1:"images/ui/skill_icons/icon_0001.webp",skill2:"images/ui/skill_icons/icon_0002.webp",skill3:"images/ui/skill_icons/icon_0003.webp",def:"images/ui/skill_icons/icon_0004.webp"},
  "이상|남부 세븐 협회 6과": {skill1:"images/ui/skill_icons/icon_0005.webp",skill2:"images/ui/skill_icons/icon_0006.webp",skill3:"images/ui/skill_icons/icon_0007.webp",def:"images/ui/skill_icons/icon_0008.webp"},
  "이상|검계 살수": {skill1:"images/ui/skill_icons/icon_0009.webp",skill2:"images/ui/skill_icons/icon_0010.webp",skill3:"images/ui/skill_icons/icon_0011.webp",def:"images/ui/skill_icons/icon_0012.webp"},
  "이상|어금니 사무소 해결사": {skill1:"images/ui/skill_icons/icon_0013.webp",skill2:"images/ui/skill_icons/icon_0014.webp",skill3:"images/ui/skill_icons/icon_0015.webp",def:"images/ui/skill_icons/icon_0016.webp"},
  "이상|W사 3등급 정리 요원": {skill1:"images/ui/skill_icons/icon_0017.webp",skill2:"images/ui/skill_icons/icon_0018.webp",skill3:"images/ui/skill_icons/icon_0019.webp",def:"images/ui/skill_icons/icon_0020.webp"},
  "이상|피쿼드호 일등 항해사": {skill1:"images/ui/skill_icons/icon_0021.webp",skill2:"images/ui/skill_icons/icon_0022.webp",skill3:"images/ui/skill_icons/icon_0023.webp",def:"images/ui/skill_icons/icon_0024.webp"},
  "이상|남부 디에치 협회 4과": {skill1:"images/ui/skill_icons/icon_0025.webp",skill2:"images/ui/skill_icons/icon_0026.webp",skill3:"images/ui/skill_icons/icon_0027.webp",def:"images/ui/skill_icons/icon_0028.webp"},
  "이상|로보토미 E.G.O::엄숙한 애도": {skill1:"images/ui/skill_icons/icon_0029.webp",skill2:"images/ui/skill_icons/icon_0030.webp",skill3:"images/ui/skill_icons/icon_0031.webp",def:"images/ui/skill_icons/icon_0032.webp"},
  "이상|남부 리우 협회 3과": {skill1:"images/ui/skill_icons/icon_0033.webp",skill2:"images/ui/skill_icons/icon_0034.webp",skill3:"images/ui/skill_icons/icon_0035.webp",def:"images/ui/skill_icons/icon_0036.webp"},
  "이상|N사 E.G.O::흉탄": {skill1:"images/ui/skill_icons/icon_0037.webp",skill2:"images/ui/skill_icons/icon_0038.webp",skill3:"images/ui/skill_icons/icon_0039.webp",def:"images/ui/skill_icons/icon_0040.webp"},
  "이상|흑수 - 오 필두": {skill1:"images/ui/skill_icons/icon_0041.webp",skill2:"images/ui/skill_icons/icon_0042.webp",skill3:"images/ui/skill_icons/icon_0043.webp",def:"images/ui/skill_icons/icon_0044.webp"},
  "이상|거미집 검지 아비": {skill1:"images/ui/skill_icons/icon_0045.webp",skill2:"images/ui/skill_icons/icon_0046.webp",skill3:"images/ui/skill_icons/icon_0047.webp",def:"images/ui/skill_icons/icon_0048.webp"},
  "이상|LCE E.G.O::차원찢개": {skill1:"images/ui/skill_icons/icon_0049.webp",skill2:"images/ui/skill_icons/icon_0050.webp",skill3:"images/ui/skill_icons/icon_0051.webp",def:"images/ui/skill_icons/icon_0052.webp"},
};

const IDENTITY_SPECIAL_SKILL_ICON_DATA = {
  "이상|흑수 - 오 필두": "images/ui/skill_icons/icon_0053.webp",
  "이상|거미집 검지 아비": "images/ui/skill_icons/icon_0054.webp",
  "이상|LCE E.G.O::차원찢개": "images/ui/skill_icons/icon_0055.webp",
};

const SIN_SKILL_FRAME_DATA = {
  "분노": {1:"images/ui/sin_frames/wrath1.webp", 2:"images/ui/sin_frames/wrath2.webp", 3:"images/ui/sin_frames/wrath3.webp"},
  "색욕": {1:"images/ui/sin_frames/lust1.webp", 2:"images/ui/sin_frames/lust2.webp", 3:"images/ui/sin_frames/lust3.webp"},
  "나태": {1:"images/ui/sin_frames/sloth1.webp", 2:"images/ui/sin_frames/sloth2.webp", 3:"images/ui/sin_frames/sloth3.webp"},
  "탐식": {1:"images/ui/sin_frames/gluttony1.webp", 2:"images/ui/sin_frames/gluttony2.webp", 3:"images/ui/sin_frames/gluttony3.webp"},
  "우울": {1:"images/ui/sin_frames/gloom1.webp", 2:"images/ui/sin_frames/gloom2.webp", 3:"images/ui/sin_frames/gloom3.webp"},
  "오만": {1:"images/ui/sin_frames/pride1.webp", 2:"images/ui/sin_frames/pride2.webp", 3:"images/ui/sin_frames/pride3.webp"},
  "질투": {1:"images/ui/sin_frames/envy1.webp", 2:"images/ui/sin_frames/envy2.webp", 3:"images/ui/sin_frames/envy3.webp"},
};

const EGO_ICON_DATA = {
  "ill-go-fer-scissors-how-bout-you-don-quixote": "images/egos/1.webp",
  "solemn-lament-yi-sang": "images/egos/2.webp",
  "into-the-sunset-rodion": "images/egos/3.webp",
  "ardor-blossom-star-faust": "images/egos/4.webp",
  "harmony-sinclair": "images/egos/5.webp",
  "move-in-reg-heathcliff": "images/egos/6.webp",
  "ill-go-fer-scissors-how-bout-you-outis": "images/egos/7.webp",
  "command-meltdown-faust": "images/egos/8.webp",
  "tidal-elegy-ishmael": "images/egos/9.webp",
  "unbrilliant-glory-gregor": "images/egos/10.webp",
  "crushbound-past-meursault": "images/egos/11.webp",
  "in-the-name-of-love-and-hate-don-quixote": "images/egos/12.webp",
  "red-sheet-don-quixote": "images/egos/13.webp",
  "indicants-trial-rodion": "images/egos/14.webp",
  "thoracalgia-faust": "images/egos/15.webp",
  "thoracalgia-ryoshu": "images/egos/16.webp",
  "magic-bullet-outis": "images/egos/17.webp",
  "christmas-nightmare-ishmael": "images/egos/18.webp",
  "christmas-nightmare-gregor": "images/egos/19.webp",
  "asymmetrical-inertia-heathcliff": "images/egos/20.webp",
  "fell-bullet-yi-sang": "images/egos/21.webp",
  "yearning-mircalla-don-quixote": "images/egos/22.webp",
  "yearning-mircalla-meursault": "images/egos/23.webp",
  "hex-nail-rodion": "images/egos/24.webp",
  "hex-nail-sinclair": "images/egos/25.webp",
  "lasso-faust": "images/egos/26.webp",
  "lasso-hong-lu": "images/egos/27.webp",
  "bygone-days-ishmael": "images/egos/28.webp",
  "solemn-lament-gregor": "images/egos/29.webp",
  "dimension-shredder-outis": "images/egos/30.webp",
  "fell-bullet-heathcliff": "images/egos/31.webp",
  "contempt-awe-ryoshu": "images/egos/32.webp",
  "everlasting-faust": "images/egos/33.webp",
  "cavernous-wailing-hong-lu": "images/egos/34.webp",
  "cavernous-wailing-sinclair": "images/egos/35.webp",
  "wingbeat-ishmael": "images/egos/36.webp",
  "sanguine-desire-rodion": "images/egos/37.webp",
  "electric-screaming-don-quixote": "images/egos/38.webp",
  "electric-screaming-meursault": "images/egos/39.webp",
  "binds-heathcliff": "images/egos/40.webp",
  "binds-outis": "images/egos/41.webp",
  "bygone-days-yi-sang": "images/egos/42.webp",
  "bygone-days-gregor": "images/egos/43.webp",
  "garden-of-thorns-gregor": "images/egos/44.webp",
  "wishing-cairn-don-quixote": "images/egos/45.webp",
  "holiday-heathcliff": "images/egos/46.webp",
  "holiday-outis": "images/egos/47.webp",
  "pursuance-rodion": "images/egos/48.webp",
  "blind-obsession-ryoshu": "images/egos/49.webp",
  "blind-obsession-ishmael": "images/egos/50.webp",
  "effervescent-corrosion-rodion": "images/egos/51.webp",
  "92-sinclair": "images/egos/52.webp",
  "92-faust": "images/egos/53.webp",
  "effervescent-corrosion-hong-lu": "images/egos/54.webp",
  "regret-meursault": "images/egos/55.webp",
  "lantern-sinclair": "images/egos/56.webp",
  "soda-ryoshu": "images/egos/57.webp",
  "soda-hong-lu": "images/egos/58.webp",
  "red-eyes-ryoshu": "images/egos/59.webp",
  "sunshower-yi-sang": "images/egos/60.webp",
  "aedd-gregor": "images/egos/61.webp",
  "aedd-heathcliff": "images/egos/62.webp",
  "sunshower-outis": "images/egos/63.webp",
  "capote-meursault": "images/egos/64.webp",
  "capote-ishmael": "images/egos/65.webp",
  "dimension-shredder-yi-sang": "images/egos/66.webp",
  "dimension-shredder-hong-lu": "images/egos/67.webp",
  "lifetime-stew-don-quixote": "images/egos/68.webp",
  "lifetime-stew-sinclair": "images/egos/69.webp",
  "telepole-faust": "images/egos/70.webp",
  "telepole-don-quixote": "images/egos/71.webp",
  "4th-match-flame-yi-sang": "images/egos/72.webp",
  "wishing-cairn-yi-sang": "images/egos/73.webp",
  "hex-nail-faust": "images/egos/74.webp",
  "fluid-sac-faust": "images/egos/75.webp",
  "fluid-sac-don-quixote": "images/egos/76.webp",
  "4th-match-flame-ryoshu": "images/egos/77.webp",
  "screwloose-wallop-meursault": "images/egos/78.webp",
  "pursuance-meursault": "images/egos/79.webp",
  "roseate-desire-hong-lu": "images/egos/80.webp",
  "telepole-heathcliff": "images/egos/81.webp",
  "roseate-desire-ishmael": "images/egos/82.webp",
  "ardor-blossom-star-ishmael": "images/egos/83.webp",
  "rime-shank-rodion": "images/egos/84.webp",
  "4th-match-flame-rodion": "images/egos/85.webp",
  "impending-day-sinclair": "images/egos/86.webp",
  "ebony-stem-outis": "images/egos/87.webp",
  "legerdemain-gregor": "images/egos/88.webp",
  "lantern-gregor": "images/egos/89.webp",
  "crows-eye-view-yi-sang": "images/egos/90.webp",
  "representation-emitter-faust": "images/egos/91.webp",
  "la-sangre-de-sancho-don-quixote": "images/egos/92.webp",
  "forest-for-the-flames-ryoshu": "images/egos/93.webp",
  "chains-of-others-meursault": "images/egos/94.webp",
  "land-of-illusion-hong-lu": "images/egos/95.webp",
  "bodysack-heathcliff": "images/egos/96.webp",
  "snagharpoon-ishmael": "images/egos/97.webp",
  "what-is-cast-rodion": "images/egos/98.webp",
  "branch-of-knowledge-sinclair": "images/egos/99.webp",
  "suddenly-one-day-gregor": "images/egos/100.webp",
  "to-páthos-máthos-outis": "images/egos/101.webp",
  "great-trichiliocosm-[三千大世界]-yi-sang": "images/egos/102.webp",
  "great-trichiliocosm-[三千大世界]-ryoshu": "images/egos/103.webp",
  "tears-of-the-tarnished-blood-[汚血泣淚]-hong-lu": "images/egos/104.webp",
  "tears-of-the-tarnished-blood-[汚血泣淚]-sinclair": "images/egos/105.webp",
  "hundred-footed-death-maggot-[蝍蛆殺]-ishmael": "images/egos/106.webp",
  "red-eyes-(open)-ryoshu": "images/egos/107.webp",
  "to-remain-oneself-[宁作吾]-hong-lu": "images/egos/108.webp",
  "ya-śunyatā-tad-rupam-heathcliff": "images/egos/109.webp",
  "ya-śunyatā-tad-rupam-outis": "images/egos/110.webp",
  "shadow-vested-bladesinger-[着影揮刀]-meursault": "images/egos/111.webp",
};

const IDENTITY_PORTRAIT_SYNCED_DATA = {
  "홍루|동부 섕크 협회 3과": "images/portraits_synced/1.webp",
  "이상|LCE E.G.O::차원찢개": "images/portraits_synced/2.webp",
  "파우스트|새벽 사무소 해결사": "images/portraits_synced/3.webp",
  "그레고르|새벽 사무소 대표": "images/portraits_synced/4.webp",
  "히스클리프|거미집 엄지 제자": "images/portraits_synced/5.webp",
  "로쟈|거미집 엄지 아비": "images/portraits_synced/6.webp",
  "홍루|S사 추노꾼": "images/portraits_synced/7.webp",
  "이스마엘|LCD 현장추리팀": "images/portraits_synced/8.webp",
  "오티스|거미집 중지 아비": "images/portraits_synced/9.webp",
  "료슈|거미집의 검": "images/portraits_synced/10.webp",
  "히스클리프|중지 작은 형님": "images/portraits_synced/11.webp",
  "뫼르소|약지 야수파 스튜던트": "images/portraits_synced/12.webp",
  "로쟈|약지 야수파 도슨트": "images/portraits_synced/13.webp",
  "파우스트|거미집 약지 제자": "images/portraits_synced/14.webp",
  "홍루|거미집 약지 아비": "images/portraits_synced/15.webp",
  "그레고르|LCE E.G.O::AEDD": "images/portraits_synced/16.webp",
  "료슈|로보토미 E.G.O::잔향 · 외로움": "images/portraits_synced/17.webp",
  "뫼르소|로보토미 E.G.O::호넷【변조】": "images/portraits_synced/18.webp",
  "이상|거미집 검지 아비": "images/portraits_synced/19.webp",
  "싱클레어|거미집 소지 제자": "images/portraits_synced/20.webp",
  "그레고르|로보토미 E.G.O::램프": "images/portraits_synced/21.webp",
  "이스마엘|거미집 중지 제자": "images/portraits_synced/22.webp",
  "돈키호테|검지 대행자 - 개화 E.G.O::대행": "images/portraits_synced/23.webp",
  "파우스트|검지 수행자:【쪽지】": "images/portraits_synced/24.webp",
  "오티스|LCA 우제트 선봉 3팀 팀장": "images/portraits_synced/25.webp",
  "로쟈|R사 제 4무리 순록팀": "images/portraits_synced/26.webp",
  "료슈|홍원 방랑무사": "images/portraits_synced/27.webp",
  "돈키호테|흑수 - 미": "images/portraits_synced/28.webp",
  "히스클리프|흑수 - 유 필두": "images/portraits_synced/29.webp",
  "이스마엘|정사무소 대표": "images/portraits_synced/30.webp",
  "그레고르|밤의 송곳 카피타노": "images/portraits_synced/31.webp",
  "뫼르소|라만차랜드 왕자": "images/portraits_synced/32.webp",
  "히스클리프|W사 4등급 정리 요원 - CCA": "images/portraits_synced/33.webp",
  "파우스트|동부 시 협회 3과": "images/portraits_synced/34.webp",
  "료슈|N사 E.G.O::경멸, 경외": "images/portraits_synced/35.webp",
  "이상|흑수 - 오 필두": "images/portraits_synced/36.webp",
  "싱클레어|흑수 - 유": "images/portraits_synced/37.webp",
  "홍루|홍원 군주": "images/portraits_synced/38.webp",
  "오티스|T사 3등급 강력징수직 직원": "images/portraits_synced/39.webp",
  "돈키호테|로보토미 E.G.O::사랑과 증오의 이름으로": "images/portraits_synced/40.webp",
  "로쟈|로보토미 E.G.O::눈물로 벼려낸 검": "images/portraits_synced/41.webp",
  "이상|N사 E.G.O::흉탄": "images/portraits_synced/42.webp",
  "뫼르소|동부 엄지 카포 IIII": "images/portraits_synced/43.webp",
  "싱클레어|동부 엄지 솔다토 II": "images/portraits_synced/44.webp",
  "이스마엘|가주 후보": "images/portraits_synced/45.webp",
  "파우스트|흑수 - 묘 필두": "images/portraits_synced/46.webp",
  "로쟈|흑수 - 사": "images/portraits_synced/47.webp",
  "그레고르|흑수 - 사": "images/portraits_synced/48.webp",
  "홍루|R사 제 4무리 순록팀": "images/portraits_synced/49.webp",
  "싱클레어|중지 작은 아우": "images/portraits_synced/50.webp",
  "료슈|흑수 - 묘": "images/portraits_synced/51.webp",
  "오티스|흑수 - 묘": "images/portraits_synced/52.webp",
  "돈키호테|동부 섕크 협회 3과": "images/portraits_synced/53.webp",
  "그레고르|불주먹 사무소 생존자": "images/portraits_synced/54.webp",
  "이상|남부 리우 협회 3과": "images/portraits_synced/55.webp",
  "히스클리프|흑운회 와카슈": "images/portraits_synced/56.webp",
  "이스마엘|흑운회 부조장": "images/portraits_synced/57.webp",
  "이상|LCE E.G.O::초롱": "images/portraits_synced/58.webp",
  "파우스트|LCE E.G.O::홍염살": "images/portraits_synced/59.webp",
  "홍루|마침표 사무소 대표": "images/portraits_synced/60.webp",
  "히스클리프|마침표 사무소 해결사": "images/portraits_synced/61.webp",
  "돈키호테|라만차랜드 실장": "images/portraits_synced/62.webp",
  "싱클레어|북부 제뱌찌 협회 3과": "images/portraits_synced/63.webp",
  "로쟈|라만차랜드 공주": "images/portraits_synced/64.webp",
  "그레고르|라만차랜드 신부": "images/portraits_synced/65.webp",
  "홍루|송곳니 사냥 사무소 해결사": "images/portraits_synced/66.webp",
  "오티스|라만차랜드 이발사": "images/portraits_synced/67.webp",
  "뫼르소|서부 섕크 협회 3과": "images/portraits_synced/68.webp",
  "싱클레어|서부 츠바이 협회 3과": "images/portraits_synced/69.webp",
  "이스마엘|서부 츠바이 협회 3과": "images/portraits_synced/70.webp",
  "로쟈|북부 제뱌찌 협회 3과": "images/portraits_synced/71.webp",
  "이상|로보토미 E.G.O::엄숙한 애도": "images/portraits_synced/72.webp",
  "료슈|로보토미 E.G.O::적안 · 참회": "images/portraits_synced/73.webp",
  "히스클리프|와일드헌트": "images/portraits_synced/74.webp",
  "파우스트|멀티크랙 사무소 대표": "images/portraits_synced/75.webp",
  "히스클리프|멀티크랙 사무소 해결사": "images/portraits_synced/76.webp",
  "오티스|W사 3등급 정리 요원 팀장": "images/portraits_synced/77.webp",
  "뫼르소|남부 디에치 협회 4과 부장": "images/portraits_synced/78.webp",
  "돈키호테|T사 3등급 징수직 직원": "images/portraits_synced/79.webp",
  "로쟈|T사 2등급 징수직 직원": "images/portraits_synced/80.webp",
  "료슈|20구 유로지비": "images/portraits_synced/81.webp",
  "홍루|20구 유로지비": "images/portraits_synced/82.webp",
  "이상|약지 점묘파 스튜던트": "images/portraits_synced/83.webp",
  "오티스|약지 점묘파 스튜던트": "images/portraits_synced/84.webp",
  "싱클레어|새벽 사무소 해결사": "images/portraits_synced/85.webp",
  "료슈|에드가 가문 치프 버틀러": "images/portraits_synced/86.webp",
  "이스마엘|에드가 가문 버틀러": "images/portraits_synced/87.webp",
  "파우스트|워더링하이츠 버틀러": "images/portraits_synced/88.webp",
  "그레고르|에드가 가문 승계자": "images/portraits_synced/89.webp",
  "뫼르소|데드레빗츠 보스": "images/portraits_synced/90.webp",
  "오티스|워더링하이츠 치프 버틀러": "images/portraits_synced/91.webp",
  "히스클리프|남부 외우피 협회 3과": "images/portraits_synced/92.webp",
  "료슈|남부 리우 협회 4과": "images/portraits_synced/93.webp",
  "로쟈|남부 리우 협회 4과 부장": "images/portraits_synced/94.webp",
  "파우스트|검계 살수": "images/portraits_synced/95.webp",
  "돈키호테|검계 살수": "images/portraits_synced/96.webp",
  "뫼르소|검계 우두머리": "images/portraits_synced/97.webp",
  "그레고르|흑운회 부조장": "images/portraits_synced/98.webp",
  "이스마엘|피쿼드호 선장": "images/portraits_synced/99.webp",
  "이상|남부 디에치 협회 4과": "images/portraits_synced/100.webp",
  "홍루|남부 디에치 협회 4과": "images/portraits_synced/101.webp",
  "돈키호테|로보토미 E.G.O::초롱": "images/portraits_synced/102.webp",
  "오티스|로보토미 E.G.O::마탄": "images/portraits_synced/103.webp",
  "싱클레어|남부 섕크 협회 4과 부장": "images/portraits_synced/104.webp",
  "오티스|남부 섕크 협회 4과": "images/portraits_synced/105.webp",
  "이상|피쿼드호 일등 항해사": "images/portraits_synced/106.webp",
  "히스클리프|피쿼드호 작살잡이": "images/portraits_synced/107.webp",
  "돈키호테|중지 작은 아우": "images/portraits_synced/108.webp",
  "뫼르소|중지 작은 아우": "images/portraits_synced/109.webp",
  "료슈|LCCB 대리": "images/portraits_synced/110.webp",
  "그레고르|쌍갈고리 해적단 부선장": "images/portraits_synced/111.webp",
  "이상|W사 3등급 정리 요원": "images/portraits_synced/112.webp",
  "파우스트|로보토미 E.G.O::후회": "images/portraits_synced/113.webp",
  "홍루|갈고리 사무소 해결사": "images/portraits_synced/114.webp",
  "로쟈|남부 디에치 협회 4과": "images/portraits_synced/115.webp",
  "이상|어금니 사무소 해결사": "images/portraits_synced/116.webp",
  "오티스|어금니 사무소 해결사": "images/portraits_synced/117.webp",
  "파우스트|남부 세븐 협회 4과": "images/portraits_synced/118.webp",
  "히스클리프|남부 세븐 협회 4과": "images/portraits_synced/119.webp",
  "료슈|W사 3등급 정리 요원": "images/portraits_synced/120.webp",
  "홍루|W사 2등급 정리 요원": "images/portraits_synced/121.webp",
  "파우스트|남부 츠바이 협회 4과": "images/portraits_synced/122.webp",
  "그레고르|남부 츠바이 협회 4과": "images/portraits_synced/123.webp",
  "이스마엘|어금니 보트 센터 해결사": "images/portraits_synced/124.webp",
  "싱클레어|어금니 보트 센터 해결사": "images/portraits_synced/125.webp",
  "돈키호테|남부 섕크 협회 5과 부장": "images/portraits_synced/126.webp",
  "뫼르소|R사 제 4무리 코뿔소팀": "images/portraits_synced/127.webp",
  "로쟈|남부 츠바이 협회 5과": "images/portraits_synced/128.webp",
  "이스마엘|남부 리우 협회 4과": "images/portraits_synced/129.webp",
  "홍루|K사 3등급 적출직 직원": "images/portraits_synced/130.webp",
  "싱클레어|로보토미 E.G.O::홍적": "images/portraits_synced/131.webp",
  "이상|개화 E.G.O::동백": "images/portraits_synced/132.webp",
  "이스마엘|로보토미 E.G.O::출렁임": "images/portraits_synced/133.webp",
  "히스클리프|로보토미 E.G.O::여우비": "images/portraits_synced/134.webp",
  "그레고르|장미스패너 공방 해결사": "images/portraits_synced/135.webp",
  "뫼르소|장미스패너 공방 해결사": "images/portraits_synced/136.webp",
  "로쟈|장미스패너 공방 대표": "images/portraits_synced/137.webp",
  "돈키호테|N사 중간 망치": "images/portraits_synced/138.webp",
  "싱클레어|쥐어들 자": "images/portraits_synced/139.webp",
  "료슈|료.고.파. 주방장": "images/portraits_synced/140.webp",
  "그레고르|료.고.파. 조수": "images/portraits_synced/141.webp",
  "홍루|남부 리우 협회 5과": "images/portraits_synced/142.webp",
  "오티스|남부 세븐 협회 6과 부장": "images/portraits_synced/143.webp",
  "파우스트|쥐는 자": "images/portraits_synced/144.webp",
  "히스클리프|N사 작은 망치": "images/portraits_synced/145.webp",
  "뫼르소|N사 큰 망치": "images/portraits_synced/146.webp",
  "로쟈|N사 중간 망치": "images/portraits_synced/147.webp",
  "이상|검계 살수": "images/portraits_synced/148.webp",
  "이상|남부 세븐 협회 6과": "images/portraits_synced/149.webp",
  "파우스트|W사 2등급 정리 요원": "images/portraits_synced/150.webp",
  "파우스트|살아남은 로보토미 직원": "images/portraits_synced/151.webp",
  "돈키호테|W사 3등급 정리 요원": "images/portraits_synced/152.webp",
  "돈키호테|남부 시 협회 5과 부장": "images/portraits_synced/153.webp",
  "료슈|흑운회 와카슈": "images/portraits_synced/154.webp",
  "료슈|남부 세븐 협회 6과": "images/portraits_synced/155.webp",
  "뫼르소|W사 2등급 정리 요원": "images/portraits_synced/156.webp",
  "뫼르소|남부 리우 협회 6과": "images/portraits_synced/157.webp",
  "홍루|콩콩이파 두목": "images/portraits_synced/158.webp",
  "홍루|흑운회 와카슈": "images/portraits_synced/159.webp",
  "히스클리프|R사 제 4무리 토끼팀": "images/portraits_synced/160.webp",
  "히스클리프|남부 시 협회 5과": "images/portraits_synced/161.webp",
  "이스마엘|R사 제 4무리 순록팀": "images/portraits_synced/162.webp",
  "이스마엘|남부 시 협회 5과": "images/portraits_synced/163.webp",
  "이스마엘|LCCB 대리": "images/portraits_synced/164.webp",
  "로쟈|흑운회 와카슈": "images/portraits_synced/165.webp",
  "로쟈|LCCB 대리": "images/portraits_synced/166.webp",
  "싱클레어|검계 살수": "images/portraits_synced/167.webp",
  "싱클레어|남부 츠바이 협회 6과": "images/portraits_synced/168.webp",
  "싱클레어|마리아치 보스": "images/portraits_synced/169.webp",
  "오티스|검계 살수": "images/portraits_synced/170.webp",
  "오티스|G사 부장": "images/portraits_synced/171.webp",
  "그레고르|G사 일등대리": "images/portraits_synced/172.webp",
  "그레고르|남부 리우 협회 6과": "images/portraits_synced/173.webp",
};

const IDENTITY_PORTRAIT_NORMAL_DATA = {
  "홍루|동부 섕크 협회 3과": "images/portraits_normal/1.webp",
  "이상|LCE E.G.O::차원찢개": "images/portraits_normal/2.webp",
  "파우스트|새벽 사무소 해결사": "images/portraits_normal/3.webp",
  "그레고르|새벽 사무소 대표": "images/portraits_normal/4.webp",
  "히스클리프|거미집 엄지 제자": "images/portraits_normal/5.webp",
  "로쟈|거미집 엄지 아비": "images/portraits_normal/6.webp",
  "홍루|S사 추노꾼": "images/portraits_normal/7.webp",
  "이스마엘|LCD 현장추리팀": "images/portraits_normal/8.webp",
  "오티스|거미집 중지 아비": "images/portraits_normal/9.webp",
  "료슈|거미집의 검": "images/portraits_normal/10.webp",
  "히스클리프|중지 작은 형님": "images/portraits_normal/11.webp",
  "뫼르소|약지 야수파 스튜던트": "images/portraits_normal/12.webp",
  "로쟈|약지 야수파 도슨트": "images/portraits_normal/13.webp",
  "파우스트|거미집 약지 제자": "images/portraits_normal/14.webp",
  "홍루|거미집 약지 아비": "images/portraits_normal/15.webp",
  "그레고르|LCE E.G.O::AEDD": "images/portraits_normal/16.webp",
  "료슈|로보토미 E.G.O::잔향 · 외로움": "images/portraits_normal/17.webp",
  "뫼르소|로보토미 E.G.O::호넷【변조】": "images/portraits_normal/18.webp",
  "이상|거미집 검지 아비": "images/portraits_normal/19.webp",
  "싱클레어|거미집 소지 제자": "images/portraits_normal/20.webp",
  "그레고르|로보토미 E.G.O::램프": "images/portraits_normal/21.webp",
  "이스마엘|거미집 중지 제자": "images/portraits_normal/22.webp",
  "돈키호테|검지 대행자 - 개화 E.G.O::대행": "images/portraits_normal/23.webp",
  "파우스트|검지 수행자:【쪽지】": "images/portraits_normal/24.webp",
  "오티스|LCA 우제트 선봉 3팀 팀장": "images/portraits_normal/25.webp",
  "로쟈|R사 제 4무리 순록팀": "images/portraits_normal/26.webp",
  "료슈|홍원 방랑무사": "images/portraits_normal/27.webp",
  "돈키호테|흑수 - 미": "images/portraits_normal/28.webp",
  "히스클리프|흑수 - 유 필두": "images/portraits_normal/29.webp",
  "이스마엘|정사무소 대표": "images/portraits_normal/30.webp",
  "그레고르|밤의 송곳 카피타노": "images/portraits_normal/31.webp",
  "뫼르소|라만차랜드 왕자": "images/portraits_normal/32.webp",
  "히스클리프|W사 4등급 정리 요원 - CCA": "images/portraits_normal/33.webp",
  "파우스트|동부 시 협회 3과": "images/portraits_normal/34.webp",
  "료슈|N사 E.G.O::경멸, 경외": "images/portraits_normal/35.webp",
  "이상|흑수 - 오 필두": "images/portraits_normal/36.webp",
  "싱클레어|흑수 - 유": "images/portraits_normal/37.webp",
  "홍루|홍원 군주": "images/portraits_normal/38.webp",
  "오티스|T사 3등급 강력징수직 직원": "images/portraits_normal/39.webp",
  "돈키호테|로보토미 E.G.O::사랑과 증오의 이름으로": "images/portraits_normal/40.webp",
  "로쟈|로보토미 E.G.O::눈물로 벼려낸 검": "images/portraits_normal/41.webp",
  "이상|N사 E.G.O::흉탄": "images/portraits_normal/42.webp",
  "뫼르소|동부 엄지 카포 IIII": "images/portraits_normal/43.webp",
  "싱클레어|동부 엄지 솔다토 II": "images/portraits_normal/44.webp",
  "이스마엘|가주 후보": "images/portraits_normal/45.webp",
  "파우스트|흑수 - 묘 필두": "images/portraits_normal/46.webp",
  "로쟈|흑수 - 사": "images/portraits_normal/47.webp",
  "그레고르|흑수 - 사": "images/portraits_normal/48.webp",
  "홍루|R사 제 4무리 순록팀": "images/portraits_normal/49.webp",
  "싱클레어|중지 작은 아우": "images/portraits_normal/50.webp",
  "료슈|흑수 - 묘": "images/portraits_normal/51.webp",
  "오티스|흑수 - 묘": "images/portraits_normal/52.webp",
  "돈키호테|동부 섕크 협회 3과": "images/portraits_normal/53.webp",
  "그레고르|불주먹 사무소 생존자": "images/portraits_normal/54.webp",
  "이상|남부 리우 협회 3과": "images/portraits_normal/55.webp",
  "히스클리프|흑운회 와카슈": "images/portraits_normal/56.webp",
  "이스마엘|흑운회 부조장": "images/portraits_normal/57.webp",
  "이상|LCE E.G.O::초롱": "images/portraits_normal/58.webp",
  "파우스트|LCE E.G.O::홍염살": "images/portraits_normal/59.webp",
  "홍루|마침표 사무소 대표": "images/portraits_normal/60.webp",
  "히스클리프|마침표 사무소 해결사": "images/portraits_normal/61.webp",
  "돈키호테|라만차랜드 실장": "images/portraits_normal/62.webp",
  "싱클레어|북부 제뱌찌 협회 3과": "images/portraits_normal/63.webp",
  "로쟈|라만차랜드 공주": "images/portraits_normal/64.webp",
  "그레고르|라만차랜드 신부": "images/portraits_normal/65.webp",
  "홍루|송곳니 사냥 사무소 해결사": "images/portraits_normal/66.webp",
  "오티스|라만차랜드 이발사": "images/portraits_normal/67.webp",
  "뫼르소|서부 섕크 협회 3과": "images/portraits_normal/68.webp",
  "싱클레어|서부 츠바이 협회 3과": "images/portraits_normal/69.webp",
  "이스마엘|서부 츠바이 협회 3과": "images/portraits_normal/70.webp",
  "로쟈|북부 제뱌찌 협회 3과": "images/portraits_normal/71.webp",
  "이상|로보토미 E.G.O::엄숙한 애도": "images/portraits_normal/72.webp",
  "료슈|로보토미 E.G.O::적안 · 참회": "images/portraits_normal/73.webp",
  "히스클리프|와일드헌트": "images/portraits_normal/74.webp",
  "파우스트|멀티크랙 사무소 대표": "images/portraits_normal/75.webp",
  "히스클리프|멀티크랙 사무소 해결사": "images/portraits_normal/76.webp",
  "오티스|W사 3등급 정리 요원 팀장": "images/portraits_normal/77.webp",
  "뫼르소|남부 디에치 협회 4과 부장": "images/portraits_normal/78.webp",
  "돈키호테|T사 3등급 징수직 직원": "images/portraits_normal/79.webp",
  "로쟈|T사 2등급 징수직 직원": "images/portraits_normal/80.webp",
  "료슈|20구 유로지비": "images/portraits_normal/81.webp",
  "홍루|20구 유로지비": "images/portraits_normal/82.webp",
  "이상|약지 점묘파 스튜던트": "images/portraits_normal/83.webp",
  "오티스|약지 점묘파 스튜던트": "images/portraits_normal/84.webp",
  "싱클레어|새벽 사무소 해결사": "images/portraits_normal/85.webp",
  "료슈|에드가 가문 치프 버틀러": "images/portraits_normal/86.webp",
  "이스마엘|에드가 가문 버틀러": "images/portraits_normal/87.webp",
  "파우스트|워더링하이츠 버틀러": "images/portraits_normal/88.webp",
  "그레고르|에드가 가문 승계자": "images/portraits_normal/89.webp",
  "뫼르소|데드레빗츠 보스": "images/portraits_normal/90.webp",
  "오티스|워더링하이츠 치프 버틀러": "images/portraits_normal/91.webp",
  "히스클리프|남부 외우피 협회 3과": "images/portraits_normal/92.webp",
  "료슈|남부 리우 협회 4과": "images/portraits_normal/93.webp",
  "로쟈|남부 리우 협회 4과 부장": "images/portraits_normal/94.webp",
  "파우스트|검계 살수": "images/portraits_normal/95.webp",
  "돈키호테|검계 살수": "images/portraits_normal/96.webp",
  "뫼르소|검계 우두머리": "images/portraits_normal/97.webp",
  "그레고르|흑운회 부조장": "images/portraits_normal/98.webp",
  "이스마엘|피쿼드호 선장": "images/portraits_normal/99.webp",
  "이상|남부 디에치 협회 4과": "images/portraits_normal/100.webp",
  "홍루|남부 디에치 협회 4과": "images/portraits_normal/101.webp",
  "돈키호테|로보토미 E.G.O::초롱": "images/portraits_normal/102.webp",
  "오티스|로보토미 E.G.O::마탄": "images/portraits_normal/103.webp",
  "싱클레어|남부 섕크 협회 4과 부장": "images/portraits_normal/104.webp",
  "오티스|남부 섕크 협회 4과": "images/portraits_normal/105.webp",
  "이상|피쿼드호 일등 항해사": "images/portraits_normal/106.webp",
  "히스클리프|피쿼드호 작살잡이": "images/portraits_normal/107.webp",
  "돈키호테|중지 작은 아우": "images/portraits_normal/108.webp",
  "뫼르소|중지 작은 아우": "images/portraits_normal/109.webp",
  "료슈|LCCB 대리": "images/portraits_normal/110.webp",
  "그레고르|쌍갈고리 해적단 부선장": "images/portraits_normal/111.webp",
  "이상|W사 3등급 정리 요원": "images/portraits_normal/112.webp",
  "파우스트|로보토미 E.G.O::후회": "images/portraits_normal/113.webp",
  "홍루|갈고리 사무소 해결사": "images/portraits_normal/114.webp",
  "로쟈|남부 디에치 협회 4과": "images/portraits_normal/115.webp",
  "이상|어금니 사무소 해결사": "images/portraits_normal/116.webp",
  "오티스|어금니 사무소 해결사": "images/portraits_normal/117.webp",
  "파우스트|남부 세븐 협회 4과": "images/portraits_normal/118.webp",
  "히스클리프|남부 세븐 협회 4과": "images/portraits_normal/119.webp",
  "료슈|W사 3등급 정리 요원": "images/portraits_normal/120.webp",
  "홍루|W사 2등급 정리 요원": "images/portraits_normal/121.webp",
  "파우스트|남부 츠바이 협회 4과": "images/portraits_normal/122.webp",
  "그레고르|남부 츠바이 협회 4과": "images/portraits_normal/123.webp",
  "이스마엘|어금니 보트 센터 해결사": "images/portraits_normal/124.webp",
  "싱클레어|어금니 보트 센터 해결사": "images/portraits_normal/125.webp",
  "돈키호테|남부 섕크 협회 5과 부장": "images/portraits_normal/126.webp",
  "뫼르소|R사 제 4무리 코뿔소팀": "images/portraits_normal/127.webp",
  "로쟈|남부 츠바이 협회 5과": "images/portraits_normal/128.webp",
  "이스마엘|남부 리우 협회 4과": "images/portraits_normal/129.webp",
  "홍루|K사 3등급 적출직 직원": "images/portraits_normal/130.webp",
  "싱클레어|로보토미 E.G.O::홍적": "images/portraits_normal/131.webp",
  "이상|개화 E.G.O::동백": "images/portraits_normal/132.webp",
  "이스마엘|로보토미 E.G.O::출렁임": "images/portraits_normal/133.webp",
  "히스클리프|로보토미 E.G.O::여우비": "images/portraits_normal/134.webp",
  "그레고르|장미스패너 공방 해결사": "images/portraits_normal/135.webp",
  "뫼르소|장미스패너 공방 해결사": "images/portraits_normal/136.webp",
  "로쟈|장미스패너 공방 대표": "images/portraits_normal/137.webp",
  "돈키호테|N사 중간 망치": "images/portraits_normal/138.webp",
  "싱클레어|쥐어들 자": "images/portraits_normal/139.webp",
  "료슈|료.고.파. 주방장": "images/portraits_normal/140.webp",
  "그레고르|료.고.파. 조수": "images/portraits_normal/141.webp",
  "홍루|남부 리우 협회 5과": "images/portraits_normal/142.webp",
  "오티스|남부 세븐 협회 6과 부장": "images/portraits_normal/143.webp",
  "파우스트|쥐는 자": "images/portraits_normal/144.webp",
  "히스클리프|N사 작은 망치": "images/portraits_normal/145.webp",
  "뫼르소|N사 큰 망치": "images/portraits_normal/146.webp",
  "로쟈|N사 중간 망치": "images/portraits_normal/147.webp",
  "이상|검계 살수": "images/portraits_normal/148.webp",
  "이상|남부 세븐 협회 6과": "images/portraits_normal/149.webp",
  "이상|LCB 수감자": "images/portraits_normal/150.webp",
  "파우스트|W사 2등급 정리 요원": "images/portraits_normal/151.webp",
  "파우스트|살아남은 로보토미 직원": "images/portraits_normal/152.webp",
  "파우스트|LCB 수감자": "images/portraits_normal/153.webp",
  "돈키호테|W사 3등급 정리 요원": "images/portraits_normal/154.webp",
  "돈키호테|남부 시 협회 5과 부장": "images/portraits_normal/155.webp",
  "돈키호테|LCB 수감자": "images/portraits_normal/156.webp",
  "료슈|흑운회 와카슈": "images/portraits_normal/157.webp",
  "료슈|남부 세븐 협회 6과": "images/portraits_normal/158.webp",
  "료슈|LCB 수감자": "images/portraits_normal/159.webp",
  "뫼르소|W사 2등급 정리 요원": "images/portraits_normal/160.webp",
  "뫼르소|남부 리우 협회 6과": "images/portraits_normal/161.webp",
  "뫼르소|LCB 수감자": "images/portraits_normal/162.webp",
  "홍루|콩콩이파 두목": "images/portraits_normal/163.webp",
  "홍루|흑운회 와카슈": "images/portraits_normal/164.webp",
  "홍루|LCB 수감자": "images/portraits_normal/165.webp",
  "히스클리프|R사 제 4무리 토끼팀": "images/portraits_normal/166.webp",
  "히스클리프|남부 시 협회 5과": "images/portraits_normal/167.webp",
  "히스클리프|LCB 수감자": "images/portraits_normal/168.webp",
  "이스마엘|R사 제 4무리 순록팀": "images/portraits_normal/169.webp",
  "이스마엘|남부 시 협회 5과": "images/portraits_normal/170.webp",
  "이스마엘|LCCB 대리": "images/portraits_normal/171.webp",
  "이스마엘|LCB 수감자": "images/portraits_normal/172.webp",
  "로쟈|흑운회 와카슈": "images/portraits_normal/173.webp",
  "로쟈|LCCB 대리": "images/portraits_normal/174.webp",
  "로쟈|LCB 수감자": "images/portraits_normal/175.webp",
  "싱클레어|검계 살수": "images/portraits_normal/176.webp",
  "싱클레어|남부 츠바이 협회 6과": "images/portraits_normal/177.webp",
  "싱클레어|마리아치 보스": "images/portraits_normal/178.webp",
  "싱클레어|LCB 수감자": "images/portraits_normal/179.webp",
  "오티스|검계 살수": "images/portraits_normal/180.webp",
  "오티스|G사 부장": "images/portraits_normal/181.webp",
  "오티스|LCB 수감자": "images/portraits_normal/182.webp",
  "그레고르|G사 일등대리": "images/portraits_normal/183.webp",
  "그레고르|남부 리우 협회 6과": "images/portraits_normal/184.webp",
  "그레고르|LCB 수감자": "images/portraits_normal/185.webp",
};

// wiki.gg 원본 크롭 없는 풀 일러스트. 라이트박스 전용. 현재는 이상(파일럿)만 있음.
const IDENTITY_PORTRAIT_FULL_DATA = {
  "이상|LCE E.G.O::차원찢개": "images/portraits_full/2.webp",
  "이상|거미집 검지 아비": "images/portraits_full/19.webp",
  "이상|흑수 - 오 필두": "images/portraits_full/36.webp",
  "이상|N사 E.G.O::흉탄": "images/portraits_full/42.webp",
  "이상|남부 리우 협회 3과": "images/portraits_full/55.webp",
  "이상|LCE E.G.O::초롱": "images/portraits_full/58.webp",
  "이상|로보토미 E.G.O::엄숙한 애도": "images/portraits_full/72.webp",
  "이상|약지 점묘파 스튜던트": "images/portraits_full/83.webp",
  "이상|남부 디에치 협회 4과": "images/portraits_full/100.webp",
  "이상|피쿼드호 일등 항해사": "images/portraits_full/106.webp",
  "이상|W사 3등급 정리 요원": "images/portraits_full/112.webp",
  "이상|어금니 사무소 해결사": "images/portraits_full/116.webp",
  "이상|개화 E.G.O::동백": "images/portraits_full/132.webp",
  "이상|검계 살수": "images/portraits_full/148.webp",
  "이상|남부 세븐 협회 6과": "images/portraits_full/149.webp",
};